@startuml cfggen
' hide the spot
hide circle

package "cfggen" {
  component "ctx" as ctx #lightblue
  component "data" as data
  component "i18n" as i18n
  component "schema" as schema
  component "value" as value
  component "write" as write
  component "genjava" as genjava
  component "gencs" as gencs
  component "genjson" as genjson
  component "genlua" as genlua
  component "gengo" as gengo
  component "gents" as gents
  component "schema.cfg" as schemacfg
  component "genbyai" as genbyai
  component "editorserver" as editorserver #lightgreen
  component "mcpserver" as mcpserver #LightPink
} 

' External Components//ffcc99
component "cfgeditor" as cfgeditor #lightgreen
component "LLM" as LLM #LightPink
component "AI agent" as agent #LightPink
component "vscode-cfg-extension" as cfgsupport #LightSalmon

folder "config" {
  [.cfg] as schemafile
  [.csv, .xlsx] as datafile
  [.json] as jsonfile
}

' Representing dependencies

' Core components managed by ctx
ctx --> schema : manages
ctx --> data : manages
ctx --> value : manages/provides access

schema --> schemacfg : parses .cfg/.xml files
data --> value : produces processed values

' Packages interacting through ctx
genjava --> ctx : interacts through
gencs --> ctx : interacts through
genjson --> ctx : interacts through
genlua --> ctx : interacts through
gengo --> ctx : interacts through
gents --> ctx : interacts through
i18n --> ctx : interacts through
genbyai --> ctx : interacts through

' Editor Server interactions
editorserver --> ctx : uses context
' MCP Server interactions
mcpserver --> ctx : read
mcpserver --> write : json
write --> datafile : write through value
write --> jsonfile : write through value

data -> schemafile : write by align
data --> datafile : read
schemacfg --> schemafile : read
value --> jsonfile : read

cfgsupport --> schemafile : highlight、go to definition、find references

' Communication between external components and configgen
cfgeditor --> editorserver : communicates with
agent --> mcpserver : queries through MCP protocol
genbyai --> LLM : uses
genbyai --> write : json
editorserver --> LLM: uses
editorserver --> write: json


@enduml